# Generated by Django 5.1 on 2025-10-21 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Park', '0002_park_park_id_ride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('visit_date', models.DateField()),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='cash', max_length=20)),
                ('sold_from', models.CharField(blank=True, choices=[('cash_counter', 'Cash Counter'), ('external_seller', 'External Seller')], max_length=20, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qr_code_path', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('checkedin_at', models.DateTimeField(blank=True, null=True)),
                ('entered', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('entry_scanned', models.BooleanField(default=False)),
                ('entryscanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Park.park')),
                ('scanned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_bookings', to=settings.AUTH_USER_MODEL)),
                ('sold_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['seller', 'cash_counter']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingRideAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allowed', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('is_addon', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_access', to='Booking.booking')),
                ('last_scanned_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ride_operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_scans', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Park.ride')),
            ],
        ),
    ]
