# Generated by Django 5.1 on 2025-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sale_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sold_from',
            field=models.CharField(blank=True, choices=[('cash_counter', 'Cash Counter'), ('external_seller', 'External Seller'), ('website', 'Website')], max_length=20, null=True),
        ),
    ]
