# Generated by Django 5.1 on 2025-10-22 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_commission_paid_booking_sale_confirmed_and_more'),
        ('Park', '0002_park_park_id_ride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('cash_counter', 'Cash Counter')], default='cash_counter', max_length=20)),
                ('additional_entries', models.PositiveIntegerField(default=0)),
                ('price_per_entry', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='Booking.booking')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Park.ride')),
                ('sold_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'cash_counter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
