# Generated by Django 5.1.2 on 2025-11-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='socks_collected',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='socks_large',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='socks_medium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='socks_small',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='socks_xlarge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
