# Generated by Django 5.1.2 on 2025-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_booking_socks_collected_booking_socks_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_arrived',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
