# Generated by Django 5.1.2 on 2026-02-15 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_booking_total_arrived'),
        ('Park', '0002_park_park_id_ride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prebooking_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=15)),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_prebooking', to='Booking.booking')),
                ('confirmed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'cash_counter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_prebookings', to=settings.AUTH_USER_MODEL)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebookings', to='Park.park')),
            ],
        ),
    ]
