# Generated by Django 5.1.2 on 2026-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_prebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='is_an_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='reference',
            field=models.CharField(blank=True, help_text="Reference for invite pre-bookings (e.g. inviter's name or contact)", max_length=255, null=True),
        ),
    ]
