# Generated by Django 5.1.2 on 2026-02-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_prebooking_is_an_invite_prebooking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='other_reference',
            field=models.CharField(blank=True, help_text='Additional reference info for invite pre-bookings', max_length=255, null=True),
        ),
    ]
