# Generated by Django 5.1.2 on 2026-02-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_prebooking_other_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_an_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='other_reference',
            field=models.CharField(blank=True, help_text='Additional reference info for invite bookings', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, help_text="Reference for invite bookings (e.g. inviter's name or contact)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status for invite pre-bookings', max_length=20),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved by admin for invite pre-booking (0 or any amount for discount)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'park_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invite_prebookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prebooking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting invite pre-booking', null=True),
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
