# Generated by Django 5.1.2 on 2026-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_booking_is_an_invite_booking_other_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
