# Generated by Django 5.1.2 on 2026-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_prebooking_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_an_offer_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer_info',
            field=models.CharField(blank=True, help_text='Details about the offer applied to this booking (if any)', max_length=255, null=True),
        ),
    ]
