# Generated by Django 5.1 on 2025-10-21 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='park_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=32)),
                ('ride_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='Park.park')),
            ],
        ),
    ]
