# Generated by Django 5.1 on 2025-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
