# Generated by Django 5.1 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0002_user_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
