# Generated by Django 5.1.2 on 2026-02-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('park_admin', 'Park Admin'), ('security', 'Security Staff'), ('ride_operator', 'Ride Operator'), ('socks_handler', 'Socks Handler'), ('seller', 'External Seller'), ('cash_counter', 'Cash Counter'), ('pre_booker', 'Pre Booker'), ('invi_pre_booker', 'Invites Pre Booker'), ('customer', 'Customer')], default='customer', max_length=32),
        ),
    ]
